### ISSUE TITLE
tokenized manifest file

### ISSUE THREAD

**Issue by mreinstein** [myrne/parse-appcache-manifest#1]
@meryn pretty cool package. For my project, I need support for parsing manifest files, but I also need to preserve comments. If I submit a pull with a new mode for tokenizing that preserves this, would you consider it? Otherwise I'll just write my own module, and I'd rather not add yet another. :)

**Comment by myrne** [comment]
Glad you like my humble little module. ;)

Given the relative simple grammar of an appcache manifest, I suppose more advanced tokenizing won't matter much in speed, so then it might as well run by default. 

How about just adding an extra property representing the intermediary result? (intermediary compared to the "aggregation" that current code does) 

And are you looking to merely tokenize the contents or also generate a parse tree of some sort?

**Comment by mreinstein** [comment]
I implemented this in my fork, the invocation is as follows:

``` coffeescript
appcacheParse  = require 'parse-appcache-manifest'
result = appcacheParse input, { tokenize: true }
```

where `result` is a flat, ordered list of tokens that comes back. 

 `input` =

```
CACHE MANIFEST

# some explicit resources
CACHE:
/happy.html
/good.css

NETWORK:
*
http://*
https://*
```

`result` =

``` json
[
  { type: 'magic signature', value: 'CACHE MANIFEST' },
  { type: 'newline' },
  { type: 'comment', value: 'some explicit resources' },
  { type: 'mode', value: 'CACHE' }
  { type: 'data', tokens: [ '/happy.html' ] },
  { type: 'data', tokens: [ '/good.css' ] },
  { type: 'newline' },
  { type: 'mode', value: 'NETWORK' }
  { type: 'data', tokens: [ '*' ] },
  { type: 'data', tokens: [ 'http://*' ] },
  { type: 'data', tokens: [ 'https://*' ] }
]
```

I've got this working in my fork. I also modified your render module and added:

``` coffeescript
appcacheRender = require 'render-appcache-manifest'
out = appcacheRender result, { tokenized: true }
```

Where `out` is a manifest text file. Happy to submit these as pull requests and open for change suggestions.

**Comment by myrne** [comment]
I've just taken a look. I think this kind of parsing would add minimal overhead. So what do you think of just adding this array as a `tokens` property to the existing result object? 

`parse(manifestContents).tokens` is not much more difficult to write than `parse(manifestContents, true)`.
The render function could then look for this `tokens` property, and, if found, use that as input and ignore the `network`, `cache`, `fallback` properties. If argument to render function is an array, it could also assume the input is an array of tokens.

With such a setup, `render(parse(manifestContents))` would be about equal to original `manifestContents`, I suppose.

I think it'd be good to add some form of tests for the tokenizing. I think if tokenizing happens by default, the correct token array should be just added to the result fixtures.

I saw you removed lib/ from gitignore with the purpose of letting it work through npm, but I don't really understand why. Because of the explicit .npmignore file in the root, npm will ignore the .gitignore file for choosing what to include in the package tarball. If I install one of the various packages I've made with such a setup, the lib directory is always included. And leaving it out the git repo means cleaner commit log, of course.

**Comment by myrne** [comment]
About the tokenizing:
How about renaming "data" to "entry", and "mode" to "section marker"?

**Comment by mreinstein** [comment]
>  So what do you think of just adding this array as a tokens property to the existing result object?

I'm fine with that.

> The render function could then look for this tokens property, and, if found, use that as input and ignore the network, cache, fallback properties.

Also sounds reasonable.

> I think if tokenizing happens by default, the correct token array should be just added to the result fixtures.

Yeah, I was planning to do this but didn't want to bother until I had a sense of whether you'd consider including this functionality or not. I can go through the tests and add assertions related to tokenizing.

> I saw you removed lib/ from gitignore with the purpose of letting it work through npm

I suppose that's fine. It's a matter of opinion, I don't think there's a right or wrong answer here. IMO I like having the actual code run by the module in version control, but I understand the elegance of not having code in git that is compiled from coffee and slightly redundant.

**Comment by mreinstein** [comment]
> How about renaming "data" to "entry", and "mode" to "section marker"?

I chose `data`, `tokens`, `line`, and `mode` based on the whatwg spec, so that it would match nicely: http://www.whatwg.org/specs/web-apps/current-work/multipage/offline.html#parsing-cache-manifests

**Comment by myrne** [comment]
> I chose data, tokens, and mode based on the whatwg spec, so that it would match nicely

Ah, you studied the spec. That makes sense. I had not looked at that before. I did it based on various examples I found on the web. Good call.

I see the spec speaks of a "data line", not "data" perse, but we could say that the token descriptors of "data" and "mode" really stand for "data line", "mode line". The fact that they are lines is implied. In other words, I'm fine with the current terminology. It's close to the spec, and adding a "line"-suffix to all these descriptors would just be more verbose without really adding anything.

**Comment by mreinstein** [comment]
> I see the spec speaks of a "data line", not "data" perse, but we could say that the token descriptors of "data" and "mode" really stand for "data line", "mode line" ... and adding a "line"-suffix to all these descriptors would just be more verbose without really adding anything.

Yeah, I was thinking about this at implementation time too. The way I interpret it is that every entity in the manifest is a line, and data and mode are 2 subtypes of those.

**Comment by myrne** [comment]
> I was planning to do this but didn't want to bother until I had a sense of whether you'd consider including this functionality or not. 

I think it's pretty cool! I do think it's a very weighty contribution to my relatively small package, which makes me wonder if it would be better if you became the maintainer of the package. I think it's relatively easy to reassign ownership on npm, although I've never done it before. I'd plea to keep my convenience properties (cache,network,fallback) in. :)

**Comment by mreinstein** [comment]
actually, re-reading the spec I think I may have botched the header detection:

> Let input be the decoded text of the manifest's byte stream.
> 
> Let position be a pointer into input, initially pointing at the first character.
> 
> If the characters starting from position are "CACHE", followed by a U+0020 SPACE character, followed by "MANIFEST", then advance position to the next character after those. Otherwise, this isn't a cache manifest; abort this algorithm with a failure while checking for the magic signature.
> 
> If the character at position is neither a U+0020 SPACE character, a U+0009 CHARACTER TABULATION (tab) character, U+000A LINE FEED (LF) character, nor a U+000D CARRIAGE RETURN (CR) character, then this isn't a cache manifest; abort this algorithm with a failure while checking for the magic signature.

I think my logic for doing this may be off slightly:

``` coffeescript
firstLine = lines.shift().trim()
  if firstLine.indexOf('CACHE MANIFEST') isnt 0
    throw new Error("Invalid cache manifest header: #{firstLine}")
```

my check would allow `CACHE MANIFEST` to be considered valid. It would also allow `CACHE MANIFESToops`. it seems that a space, tab, carriage return or linefeed MUST follow. Does that seem right?

I realize this is probably not THAT big of a deal but might as well get it as close as possible to the spec.

**Comment by myrne** [comment]
What you say seems right. Also, the `trim` at first probably must go, because it would allow leading whitespace. So I guess check if CACHE MANIFEST appears first, then check, the trailing characters. I'm very bad at writing regexes, but something like `/^CACHE MANIFEST(\s*)$/` or so?

**Comment by mreinstein** [comment]
> which makes me wonder if it would be better if you became the maintainer of the package

Definitely not my goal. My primary motivation is to contribute to an existing module and make it better, rather than creating an entirely new package. I think there's far too much of that as it is. If we all put more effort into working together, package discovery would get easier, and we'd spend less time re-inventing the wheel. :)

> I think it's relatively easy to reassign ownership

I think you should keep ownership of the package. I don't foresee making a lot of additional changes at this point, apart from a few simple improvements here and there. But I'm happy to help you with maintainence, bouncing ideas off of, etc!

> So I guess check if CACHE MANIFEST appears first, then check, the trailing characters.

I'll work on fixing the header check, changing the api signature to match what we talked about, updating the README, and restoring the lib/ reference in .gitignore. I should have something for you by this evening.

**Comment by mreinstein** [comment]
closed via pull request https://github.com/meryn/parse-appcache-manifest/pull/2
